services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-container
    environment:
      - 'MYSQL_DATABASE=interest_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
